### ISSUE TITLE
Getting an error when trying to install

### ISSUE THREAD

**Issue by farzadmf** [maaslalani/draw#1]
**Describe the bug**
I'm trying to use `go install`, but I'm getting an error:
```
go: downloading github.com/maaslalani/draw v0.1.0
go: github.com/maaslalani/draw@latest: github.com/maaslalani/draw@v0.1.0: verifying module: checksum mismatch
        downloaded: h1:JSQ6SjhXQwc3SXVxAX9INRIdfAs805RkeHWVcNdCe1s=
        sum.golang.org: h1:rlLEsE55Zpv2dmC8r0A3Z59tKx3l8TPPY+fNwlAnnsw=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

Not sure if it's an issue with my setup TBH, but that's unlikely because I don't have this issue with other Go binaries I try to install.

**To Reproduce**
Run `go install github.com/maaslalani/draw@latest` in the terminal

**Expected behavior**
I should be able to install the binary

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by maaslalani** [comment]
Hey! Thanks for reporting this issue: I just made a new release and that should solve what you are seeing.

Could you try the command again?
```
go install github.com/maaslalani/draw@latest
```

if that doesn't work try installing `@main` instead of `@latest`

```
```

**Comment by farzadmf** [comment]
Thank you @maaslalani , the new release seems to work. Closing this as it's resolved now
