### ISSUE TITLE
Alt+0-9 Doesn't Insert the Number

### ISSUE THREAD

**Issue by ghost** [maaslalani/draw#14]
**Describe the bug**
As per the [documentation](https://github.com/maaslalani/draw#controls), `Alt+[0-9]` is supposed to allow us to draw with the selected number. However, when applying that combination, it seems to draw a literal `Alt+[0-9]` on the canvas.
This also applies to insert mode.

**To Reproduce**
1. Open a blank canvas
2. Press `Alt+[0-9]`
3. Try to draw something

**Expected behavior**
When pressing `Alt+[0-9]`, I expect it to allow me to draw with the number. The same thing applies to insert mode. Right now, I can't insert a number!

**Screenshots**
![image](https://user-images.githubusercontent.com/82761116/211631311-4f2819c7-7b69-4891-952c-c9983bd56447.png)

**Desktop (please complete the following information):**
 - Arch: x86_64 
 - OS: GNU/Linux
 - Terminal: st
 - Version: v0.1.1

**Additional context**
N/A

**Comment by HelionSmoker** [comment]
Turns out, the the release is outdated and doesn't feature the newest changes. After compiling from source code, I got it to work!

**Comment by maaslalani** [comment]
Hey @HelionSmoker, thanks for using draw and creating this issue! Glad you were able to resolve it ❤️

**Comment by HelionSmoker** [comment]
> Hey @HelionSmoker, thanks for using draw and creating this issue! Glad you were able to resolve it heart

I'd love to see an update on the Release page soon, so that new users don't have to deal with this, but maybe you're waiting on some other features before making a new release?
