### ISSUE TITLE
bash: draw: command not found

### ISSUE THREAD

**Issue by msr8** [maaslalani/draw#4]
**Describe the bug**
I just installed the program by running `go install github.com/maaslalani/draw@latest` and it says that the command is not found even after I restarted my terminal

**To Reproduce**
1) Be on MacOS
2) Install go via homebrew by doing `brew install go`
3) Install draw by doing `go install github.com/maaslalani/draw@latest`

**Expected behavior**
The program is supposed to be ran

**Screenshots**
![Screenshot 2022-04-17 at 00 27 31](https://user-images.githubusercontent.com/79649185/163687961-8d6d3df9-6fe3-4efc-a59c-dbb046f757ff.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.2 (Catalina)

Additional Info:
![image](https://user-images.githubusercontent.com/79649185/163688011-0d82ae5b-6392-43aa-87b0-8cd34eccf24e.png)

**Comment by maaslalani** [comment]
Hi! I imagine this is because your `GOBIN` is not set or it is not added to your `PATH`.

Try this and try running `draw` again.

```
PATH=$PATH:$HOME/go/bin
```

Alternatively, you could execute `$HOME/go/bin/draw`.

**Comment by maaslalani** [comment]
Feel free to reopen this issue if adding your `$GOBIN` to your `PATH` doesn't solve the issue!

**Comment by msr8** [comment]
That worked, thank you!
