### ISSUE TITLE
[FEATURE REQUEST] Makefile addition to draw

### ISSUE THREAD

**Issue by ThamognyaKodi** [maaslalani/draw#7]
**Is your feature request related to a problem? Please describe.**

I would like to request a Makefile with an `INSTALL_DIR` variable that allows people to install it via a AUR or Gentoo Ebuild

**Describe the solution you'd like**
 I would like a `Makefile` with a minimum of an install variable

 **Describe alternatives you've considered**
 Unfortunately due to the packaging style of the tar.gz file, a Makefile is required for Gentoo Ebuilds. There are no other ways apart from add a patch on the package-manager's side.

**Comment by maaslalani** [comment]
Seems very reasonable to me. Thank you so much for making the PR as well!
